## In Class Graphical User Interface Notes

```{r}
UScrimes <- function(urbanpopulation) {
```

Testing UI Components:
```{r}
testMyUI <- function(UI, serverFun=function(input,output){})
  {
    runApp(list(ui=bootstrapPage(UI),
                server = serverFun)
           )
    }
```

Common Compondents of a UI:
```{r}
choicesCheckbox <- checkboxGroupInput(inputId="InputA",
                                      label="Prevalence: People",
                                      choices=list(
                                        "Susceptibles"="showS",
                                        "Infectives"="showI",
                                        "Recovered"="showR",
                                        "Total Population"="showPop"),
                                      selected=c("infectives","susceptibles")
                                      )
```

## Multiplayer App (Working to Create a Server)
```{r}
drawDistribution <- function(fun=dbeta,param1=1,param2=.5,xlim=c(0,1),xdata=NULL){
  x <- seq(xlim[1],xlim[2],length=200)
  y <- fun(x, param1,param2)
  # Get rid of points not in the domain of the distribution
  keep <- is.finite(y)
  y <- y[keep]
  x <- x[keep]
  plot(x,y,type='l',xlim=xlim,lwd=2,col="red",ylim=c(0,max(y)),
       ylab="Probability Density", xlab="x", bty="n")
  if (!is.null(xdata)) {
    points( xdata, rep(0,length(xdata) ), 
            pch=20, col=rgb(0,0,0,.1) )
    dens <- density(xdata)
    lines( dens$x, dens$y )
    }
  }
```